# Generated by Django 4.2.6 on 2023-10-28 23:56

from django.db import migrations, connection

def create_pg_trgm_extension(apps, schema_editor):
    # Only execute the command if the database is PostgreSQL
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.RunPython(create_pg_trgm_extension),
    ]
